//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MasterjaJP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MasterjaJP() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MasterjaJP", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /HelpAdminjp/index.html.
        /// </summary>
        internal static string hdnHelp {
            get {
                return ResourceManager.GetString("hdnHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://docs.google.com/presentation/d/e/2PACX-1vQgok_lCuOvuv7X_X-pZ2YmJlncl8GNn1EJiLu29TOlXB_mK1GYePvXGoCC2kbVNnT-9BXOgZBHGJyH/pub?start=false&amp;loop=false&amp;delayms=3000.
        /// </summary>
        internal static string hdnHelpPresentation {
            get {
                return ResourceManager.GetString("hdnHelpPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JapaneseChineseKanjiLabel {
            get {
                return ResourceManager.GetString("JapaneseChineseKanjiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カンジ.
        /// </summary>
        internal static string JapaneseChineseLabel {
            get {
                return ResourceManager.GetString("JapaneseChineseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ピンイン.
        /// </summary>
        internal static string JapaneseChineseRomanjiLabel {
            get {
                return ResourceManager.GetString("JapaneseChineseRomanjiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カンジ.
        /// </summary>
        internal static string JapaneseJapaneseKanjiLabel {
            get {
                return ResourceManager.GetString("JapaneseJapaneseKanjiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 簡体.
        /// </summary>
        internal static string JapaneseJapaneseLabel {
            get {
                return ResourceManager.GetString("JapaneseJapaneseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ローマ字.
        /// </summary>
        internal static string JapaneseJapaneseRomanjiLabel {
            get {
                return ResourceManager.GetString("JapaneseJapaneseRomanjiLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリー一括吸上げ.
        /// </summary>
        internal static string lblCategoryBulkUpload {
            get {
                return ResourceManager.GetString("lblCategoryBulkUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to カテゴリー管理画面.
        /// </summary>
        internal static string lblCategoryMaintenance {
            get {
                return ResourceManager.GetString("lblCategoryMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to クラス管理画面.
        /// </summary>
        internal static string lblClassMaintenance {
            get {
                return ResourceManager.GetString("lblClassMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 新しいユーザーIDを作成.
        /// </summary>
        internal static string lblCreateStudent {
            get {
                return ResourceManager.GetString("lblCreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound Upload.
        /// </summary>
        internal static string lblFileUploader {
            get {
                return ResourceManager.GetString("lblFileUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フィルター管理画面.
        /// </summary>
        internal static string lblFilterMaintenance {
            get {
                return ResourceManager.GetString("lblFilterMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to フリーメッセージ閲覧.
        /// </summary>
        internal static string lblFreeMessageView {
            get {
                return ResourceManager.GetString("lblFreeMessageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ヘルプ.
        /// </summary>
        internal static string lblHelp {
            get {
                return ResourceManager.GetString("lblHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ホーム.
        /// </summary>
        internal static string lblHome {
            get {
                return ResourceManager.GetString("lblHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image Upload.
        /// </summary>
        internal static string lblImageUploader {
            get {
                return ResourceManager.GetString("lblImageUploader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログアウト.
        /// </summary>
        internal static string lblLogout {
            get {
                return ResourceManager.GetString("lblLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール閲覧.
        /// </summary>
        internal static string lblMailExchangeReport {
            get {
                return ResourceManager.GetString("lblMailExchangeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メールチェック.
        /// </summary>
        internal static string lblMailMonitoring {
            get {
                return ResourceManager.GetString("lblMailMonitoring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to メール統計レポート.
        /// </summary>
        internal static string lblMailStatisticsReport {
            get {
                return ResourceManager.GetString("lblMailStatisticsReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        internal static string lblMaintenance {
            get {
                return ResourceManager.GetString("lblMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Pool.
        /// </summary>
        internal static string lblMessagePoll {
            get {
                return ResourceManager.GetString("lblMessagePoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string lblName {
            get {
                return ResourceManager.GetString("lblName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ニュース編集画面.
        /// </summary>
        internal static string lblNoticeUpdateTool {
            get {
                return ResourceManager.GetString("lblNoticeUpdateTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パレットのインポート&lt;br/&gt;/エクスポート.
        /// </summary>
        internal static string lblPaletteImportExport {
            get {
                return ResourceManager.GetString("lblPaletteImportExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パレット管理画面.
        /// </summary>
        internal static string lblPaletteMaintenance {
            get {
                return ResourceManager.GetString("lblPaletteMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 記録.
        /// </summary>
        internal static string lblReports {
            get {
                return ResourceManager.GetString("lblReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 学校情報管理画面.
        /// </summary>
        internal static string lblSchoolMaintenance {
            get {
                return ResourceManager.GetString("lblSchoolMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 送信メールの削除.
        /// </summary>
        internal static string lblSentMail {
            get {
                return ResourceManager.GetString("lblSentMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー管理画面(備考).
        /// </summary>
        internal static string lblStudentProgress {
            get {
                return ResourceManager.GetString("lblStudentProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk Matching Settings.
        /// </summary>
        internal static string lblTalkMatchingSettings {
            get {
                return ResourceManager.GetString("lblTalkMatchingSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk Monitor.
        /// </summary>
        internal static string lblTalkMonitor {
            get {
                return ResourceManager.GetString("lblTalkMonitor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Talk Calendar Settings.
        /// </summary>
        internal static string lblTalkSchedulerTimeSettings {
            get {
                return ResourceManager.GetString("lblTalkSchedulerTimeSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ツール.
        /// </summary>
        internal static string lblTool {
            get {
                return ResourceManager.GetString("lblTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to トピック編集画面.
        /// </summary>
        internal static string lblTopicUpdateTool {
            get {
                return ResourceManager.GetString("lblTopicUpdateTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー一括登録.
        /// </summary>
        internal static string lblUserBulkUpload {
            get {
                return ResourceManager.GetString("lblUserBulkUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 登録者数.
        /// </summary>
        internal static string lblUserListReport {
            get {
                return ResourceManager.GetString("lblUserListReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ログイン状況.
        /// </summary>
        internal static string lblUserLoginReport {
            get {
                return ResourceManager.GetString("lblUserLoginReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ユーザー管理画面(メイン).
        /// </summary>
        internal static string lblUserMaintenance {
            get {
                return ResourceManager.GetString("lblUserMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ワード管理画面.
        /// </summary>
        internal static string lblWordMaintenance {
            get {
                return ResourceManager.GetString("lblWordMaintenance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to パレット一括登録.
        /// </summary>
        internal static string lblWordPaletteBulkUpload {
            get {
                return ResourceManager.GetString("lblWordPaletteBulkUpload", resourceCulture);
            }
        }
    }
}
