//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.Discovery.MiscService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MiscService.IMiscService")]
    public interface IMiscService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCountryList", ReplyAction="http://tempuri.org/IMiscService/GetCountryListResponse")]
        string GetCountryList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCountryList", ReplyAction="http://tempuri.org/IMiscService/GetCountryListResponse")]
        System.Threading.Tasks.Task<string> GetCountryListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityList", ReplyAction="http://tempuri.org/IMiscService/GetCityListResponse")]
        string GetCityList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityList", ReplyAction="http://tempuri.org/IMiscService/GetCityListResponse")]
        System.Threading.Tasks.Task<string> GetCityListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetClassList", ReplyAction="http://tempuri.org/IMiscService/GetClassListResponse")]
        string GetClassList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetClassList", ReplyAction="http://tempuri.org/IMiscService/GetClassListResponse")]
        System.Threading.Tasks.Task<string> GetClassListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetUserTypeList", ReplyAction="http://tempuri.org/IMiscService/GetUserTypeListResponse")]
        string GetUserTypeList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetUserTypeList", ReplyAction="http://tempuri.org/IMiscService/GetUserTypeListResponse")]
        System.Threading.Tasks.Task<string> GetUserTypeListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityListByCountry", ReplyAction="http://tempuri.org/IMiscService/GetCityListByCountryResponse")]
        string GetCityListByCountry(int countryid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityListByCountry", ReplyAction="http://tempuri.org/IMiscService/GetCityListByCountryResponse")]
        System.Threading.Tasks.Task<string> GetCityListByCountryAsync(int countryid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityListByCountryAndLanguage", ReplyAction="http://tempuri.org/IMiscService/GetCityListByCountryAndLanguageResponse")]
        string GetCityListByCountryAndLanguage(int countryid, string languagecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityListByCountryAndLanguage", ReplyAction="http://tempuri.org/IMiscService/GetCityListByCountryAndLanguageResponse")]
        System.Threading.Tasks.Task<string> GetCityListByCountryAndLanguageAsync(int countryid, string languagecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetInterestList", ReplyAction="http://tempuri.org/IMiscService/GetInterestListResponse")]
        string GetInterestList(string langaugeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetInterestList", ReplyAction="http://tempuri.org/IMiscService/GetInterestListResponse")]
        System.Threading.Tasks.Task<string> GetInterestListAsync(string langaugeCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetLanguageList", ReplyAction="http://tempuri.org/IMiscService/GetLanguageListResponse")]
        string GetLanguageList();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetLanguageList", ReplyAction="http://tempuri.org/IMiscService/GetLanguageListResponse")]
        System.Threading.Tasks.Task<string> GetLanguageListAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetSchoolList", ReplyAction="http://tempuri.org/IMiscService/GetSchoolListResponse")]
        string GetSchoolList(string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetSchoolList", ReplyAction="http://tempuri.org/IMiscService/GetSchoolListResponse")]
        System.Threading.Tasks.Task<string> GetSchoolListAsync(string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetLevelList", ReplyAction="http://tempuri.org/IMiscService/GetLevelListResponse")]
        string GetLevelList(string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetLevelList", ReplyAction="http://tempuri.org/IMiscService/GetLevelListResponse")]
        System.Threading.Tasks.Task<string> GetLevelListAsync(string language);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetAboutMeList", ReplyAction="http://tempuri.org/IMiscService/GetAboutMeListResponse")]
        string GetAboutMeList(string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetAboutMeList", ReplyAction="http://tempuri.org/IMiscService/GetAboutMeListResponse")]
        System.Threading.Tasks.Task<string> GetAboutMeListAsync(string languageCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityOtherName", ReplyAction="http://tempuri.org/IMiscService/GetCityOtherNameResponse")]
        string GetCityOtherName(int cityid, string languagecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityOtherName", ReplyAction="http://tempuri.org/IMiscService/GetCityOtherNameResponse")]
        System.Threading.Tasks.Task<string> GetCityOtherNameAsync(int cityid, string languagecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityListByLanguage", ReplyAction="http://tempuri.org/IMiscService/GetCityListByLanguageResponse")]
        string GetCityListByLanguage(string languagecode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMiscService/GetCityListByLanguage", ReplyAction="http://tempuri.org/IMiscService/GetCityListByLanguageResponse")]
        System.Threading.Tasks.Task<string> GetCityListByLanguageAsync(string languagecode);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMiscServiceChannel : Language.Discovery.MiscService.IMiscService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MiscServiceClient : System.ServiceModel.ClientBase<Language.Discovery.MiscService.IMiscService>, Language.Discovery.MiscService.IMiscService {
        
        public MiscServiceClient() {
        }
        
        public MiscServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MiscServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiscServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MiscServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetCountryList() {
            return base.Channel.GetCountryList();
        }
        
        public System.Threading.Tasks.Task<string> GetCountryListAsync() {
            return base.Channel.GetCountryListAsync();
        }
        
        public string GetCityList() {
            return base.Channel.GetCityList();
        }
        
        public System.Threading.Tasks.Task<string> GetCityListAsync() {
            return base.Channel.GetCityListAsync();
        }
        
        public string GetClassList() {
            return base.Channel.GetClassList();
        }
        
        public System.Threading.Tasks.Task<string> GetClassListAsync() {
            return base.Channel.GetClassListAsync();
        }
        
        public string GetUserTypeList() {
            return base.Channel.GetUserTypeList();
        }
        
        public System.Threading.Tasks.Task<string> GetUserTypeListAsync() {
            return base.Channel.GetUserTypeListAsync();
        }
        
        public string GetCityListByCountry(int countryid) {
            return base.Channel.GetCityListByCountry(countryid);
        }
        
        public System.Threading.Tasks.Task<string> GetCityListByCountryAsync(int countryid) {
            return base.Channel.GetCityListByCountryAsync(countryid);
        }
        
        public string GetCityListByCountryAndLanguage(int countryid, string languagecode) {
            return base.Channel.GetCityListByCountryAndLanguage(countryid, languagecode);
        }
        
        public System.Threading.Tasks.Task<string> GetCityListByCountryAndLanguageAsync(int countryid, string languagecode) {
            return base.Channel.GetCityListByCountryAndLanguageAsync(countryid, languagecode);
        }
        
        public string GetInterestList(string langaugeCode) {
            return base.Channel.GetInterestList(langaugeCode);
        }
        
        public System.Threading.Tasks.Task<string> GetInterestListAsync(string langaugeCode) {
            return base.Channel.GetInterestListAsync(langaugeCode);
        }
        
        public string GetLanguageList() {
            return base.Channel.GetLanguageList();
        }
        
        public System.Threading.Tasks.Task<string> GetLanguageListAsync() {
            return base.Channel.GetLanguageListAsync();
        }
        
        public string GetSchoolList(string language) {
            return base.Channel.GetSchoolList(language);
        }
        
        public System.Threading.Tasks.Task<string> GetSchoolListAsync(string language) {
            return base.Channel.GetSchoolListAsync(language);
        }
        
        public string GetLevelList(string language) {
            return base.Channel.GetLevelList(language);
        }
        
        public System.Threading.Tasks.Task<string> GetLevelListAsync(string language) {
            return base.Channel.GetLevelListAsync(language);
        }
        
        public string GetAboutMeList(string languageCode) {
            return base.Channel.GetAboutMeList(languageCode);
        }
        
        public System.Threading.Tasks.Task<string> GetAboutMeListAsync(string languageCode) {
            return base.Channel.GetAboutMeListAsync(languageCode);
        }
        
        public string GetCityOtherName(int cityid, string languagecode) {
            return base.Channel.GetCityOtherName(cityid, languagecode);
        }
        
        public System.Threading.Tasks.Task<string> GetCityOtherNameAsync(int cityid, string languagecode) {
            return base.Channel.GetCityOtherNameAsync(cityid, languagecode);
        }
        
        public string GetCityListByLanguage(string languagecode) {
            return base.Channel.GetCityListByLanguage(languagecode);
        }
        
        public System.Threading.Tasks.Task<string> GetCityListByLanguageAsync(string languagecode) {
            return base.Channel.GetCityListByLanguageAsync(languagecode);
        }
    }
}
