//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Language.Discovery.Admin.ReportService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportService.IReportService")]
    public interface IReportService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetMailExhangeLogReport", ReplyAction="http://tempuri.org/IReportService/GetMailExhangeLogReportResponse")]
        string GetMailExhangeLogReport(int schoolID, string sender, string recipient, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetMailExhangeLogReport", ReplyAction="http://tempuri.org/IReportService/GetMailExhangeLogReportResponse")]
        System.Threading.Tasks.Task<string> GetMailExhangeLogReportAsync(int schoolID, string sender, string recipient, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetUserLoginReport", ReplyAction="http://tempuri.org/IReportService/GetUserLoginReportResponse")]
        string GetUserLoginReport(int schoolID, string username, string sort, string order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetUserLoginReport", ReplyAction="http://tempuri.org/IReportService/GetUserLoginReportResponse")]
        System.Threading.Tasks.Task<string> GetUserLoginReportAsync(int schoolID, string username, string sort, string order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetUserListReport", ReplyAction="http://tempuri.org/IReportService/GetUserListReportResponse")]
        string GetUserListReport(int schoolID, string username, string sort, string order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetUserListReport", ReplyAction="http://tempuri.org/IReportService/GetUserListReportResponse")]
        System.Threading.Tasks.Task<string> GetUserListReportAsync(int schoolID, string username, string sort, string order);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetMailExhangeStatistics", ReplyAction="http://tempuri.org/IReportService/GetMailExhangeStatisticsResponse")]
        string GetMailExhangeStatistics(int schoolID, string sender, string recipient, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportService/GetMailExhangeStatistics", ReplyAction="http://tempuri.org/IReportService/GetMailExhangeStatisticsResponse")]
        System.Threading.Tasks.Task<string> GetMailExhangeStatisticsAsync(int schoolID, string sender, string recipient, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportServiceChannel : Language.Discovery.Admin.ReportService.IReportService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportServiceClient : System.ServiceModel.ClientBase<Language.Discovery.Admin.ReportService.IReportService>, Language.Discovery.Admin.ReportService.IReportService {
        
        public ReportServiceClient() {
        }
        
        public ReportServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetMailExhangeLogReport(int schoolID, string sender, string recipient, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            return base.Channel.GetMailExhangeLogReport(schoolID, sender, recipient, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<string> GetMailExhangeLogReportAsync(int schoolID, string sender, string recipient, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            return base.Channel.GetMailExhangeLogReportAsync(schoolID, sender, recipient, startDate, endDate);
        }
        
        public string GetUserLoginReport(int schoolID, string username, string sort, string order) {
            return base.Channel.GetUserLoginReport(schoolID, username, sort, order);
        }
        
        public System.Threading.Tasks.Task<string> GetUserLoginReportAsync(int schoolID, string username, string sort, string order) {
            return base.Channel.GetUserLoginReportAsync(schoolID, username, sort, order);
        }
        
        public string GetUserListReport(int schoolID, string username, string sort, string order) {
            return base.Channel.GetUserListReport(schoolID, username, sort, order);
        }
        
        public System.Threading.Tasks.Task<string> GetUserListReportAsync(int schoolID, string username, string sort, string order) {
            return base.Channel.GetUserListReportAsync(schoolID, username, sort, order);
        }
        
        public string GetMailExhangeStatistics(int schoolID, string sender, string recipient, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            return base.Channel.GetMailExhangeStatistics(schoolID, sender, recipient, startDate, endDate);
        }
        
        public System.Threading.Tasks.Task<string> GetMailExhangeStatisticsAsync(int schoolID, string sender, string recipient, System.Nullable<System.DateTime> startDate, System.Nullable<System.DateTime> endDate) {
            return base.Channel.GetMailExhangeStatisticsAsync(schoolID, sender, recipient, startDate, endDate);
        }
    }
}
